In [8]:
career_dict['resultSets'][0].keys()

dict_keys(['name', 'headers', 'rowSet'])

In [7]:
cols = career_dict['resultSets'][0]['headers']
print(cols)

['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE']

In [12]:
from nba_api.stats.endpoints import playergamelog

# Nikola Jokić
career = playergamelog.PlayerGameLog(player_id='1627759', season='2024-25')

career_dict = career.get_dict()

career.get_dict()

{'resource': 'playergamelog',
 'parameters': {'PlayerID': 1627759,
  'LeagueID': None,
  'Season': '2024-25',
  'SeasonType': 'Regular Season',
  'DateFrom': None,
  'DateTo': None},
 'resultSets': [{'name': 'PlayerGameLog',
   'headers': ['SEASON_ID',
    'Player_ID',
    'Game_ID',
    'GAME_DATE',
    'MATCHUP',
    'WL',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS',
    'PLUS_MINUS',
    'VIDEO_AVAILABLE'],
   'rowSet': [['22024',
     1627759,
     '0022400891',
     'MAR 05, 2025',
     'BOS vs. POR',
     'W',
     40,
     7,
     23,
     0.304,
     0,
     4,
     0.0,
     4,
     6,
     0.667,
     3,
     5,
     8,
     8,
     1,
     0,
     3,
     2,
     18,
     15,
     1],
    ['22024',
     1627759,
     '0022400866',
     'MAR 02, 2025',
     'BOS vs. DEN',
     'W',
     37,
     6,
     15,
     0.4,
     2,
     4,
     0.5,
     8,
     9,
     0.889,
     0,
     5,
     5,
     8,
     2,
     2,
     5,
     2,
     22,
     10,
     1],
    ['22024',
     1627759,
     '0022400852',
     'FEB 28, 2025',
     'BOS vs. CLE',
     'L',
     34,
     13,
     24,
     0.542,
     4,
     6,
     0.667,
     7,
     10,
     0.7,
     4,
     1,
     5,
     2,
     0,
     0,
     3,
     4,
     37,
     10,
     1],
    ['22024',
     1627759,
     '0022400829',
     'FEB 25, 2025',
     'BOS @ TOR',
     'W',
     33,
     10,
     18,
     0.556,
     0,
     5,
     0.0,
     4,
     4,
     1.0,
     1,
     4,
     5,
     4,
     1,
     0,
     3,
     1,
     24,
     5,
     1],
    ['22024',
     1627759,
     '0022400811',
     'FEB 23, 2025',
     'BOS vs. NYK',
     'W',
     37,
     10,
     21,
     0.476,
     2,
     7,
     0.286,
     2,
     2,
     1.0,
     1,
     7,
     8,
     2,
     2,
     0,
     2,
     2,
     24,
     14,
     1],
    ['22024',
     1627759,
     '0022400789',
     'FEB 20, 2025',
     'BOS @ PHI',
     'W',
     27,
     7,
     13,
     0.538,
     2,
     6,
     0.333,
     4,
     4,
     1.0,
     3,
     3,
     6,
     6,
     0,
     0,
     3,
     1,
     20,
     6,
     1],
    ['22024',
     1627759,
     '0022400748',
     'FEB 08, 2025',
     'BOS @ NYK',
     'W',
     32,
     5,
     14,
     0.357,
     0,
     3,
     0.0,
     2,
     2,
     1.0,
     1,
     2,
     3,
     5,
     3,
     1,
     4,
     3,
     12,
     9,
     1],
    ['22024',
     1627759,
     '0022400728',
     'FEB 06, 2025',
     'BOS vs. DAL',
     'L',
     33,
     9,
     16,
     0.563,
     3,
     4,
     0.75,
     4,
     4,
     1.0,
     0,
     5,
     5,
     2,
     1,
     0,
     3,
     1,
     25,
     -15,
     1],
    ['22024',
     1627759,
     '0022400710',
     'FEB 04, 2025',
     'BOS @ CLE',
     'W',
     28,
     7,
     12,
     0.583,
     0,
     0,
     0.0,
     2,
     2,
     1.0,
     2,
     7,
     9,
     6,
     0,
     0,
     5,
     5,
     16,
     -9,
     1],
    ['22024',
     1627759,
     '0022400698',
     'FEB 02, 2025',
     'BOS @ PHI',
     'W',
     42,
     9,
     17,
     0.529,
     2,
     7,
     0.286,
     1,
     2,
     0.5,
     3,
     7,
     10,
     6,
     1,
     0,
     2,
     4,
     21,
     17,
     1],
    ['22024',
     1627759,
     '0022400683',
     'JAN 31, 2025',
     'BOS @ NOP',
     'W',
     35,
     11,
     18,
     0.611,
     3,
     6,
     0.5,
     3,
     4,
     0.75,
     1,
     5,
     6,
     4,
     0,
     0,
     1,
     4,
     28,
     2,
     1],
    ['22024',
     1627759,
     '0022400666',
     'JAN 29, 2025',
     'BOS vs. CHI',
     'W',
     36,
     10,
     18,
     0.556,
     1,
     5,
     0.2,
     7,
     11,
     0.636,
     0,
     6,
     6,
     6,
     1,
     0,
     0,
     3,
     28,
     23,
     1],
    ['22024',
     1627759,
     '0022400650',
     'JAN 27, 2025',
     'BOS vs. HOU',
     'L',
     38,
     10,
     23,
     0.435,
     3,
     9,
     0.333,
     5,
     6,
     0.833,
     0,
     4,
     4,
     4,
     0,
     1,
     2,
     4,
     28,
     -12,
     1],
    ['22024',
     1627759,
     '0022400635',
     'JAN 25, 2025',
     'BOS @ DAL',
     'W',
     31,
     10,
     21,
     0.476,
     0,
     5,
     0.0,
     2,
     6,
     0.333,
     1,
     7,
     8,
     6,
     0,
     0,
     0,
     4,
     22,
     10,
     1],
    ['22024',
     1627759,
     '0022400629',
     'JAN 23, 2025',
     'BOS @ LAL',
     'L',
     33,
     7,
     19,
     0.368,
     3,
     9,
     0.333,
     0,
     3,
     0.0,
     2,
     6,
     8,
     3,
     1,
     0,
     0,
     2,
     17,
     -18,
     1],
    ['22024',
     1627759,
     '0022400620',
     'JAN 22, 2025',
     'BOS @ LAC',
     'W',
     39,
     8,
     15,
     0.533,
     2,
     2,
     1.0,
     7,
     9,
     0.778,
     0,
     2,
     2,
     6,
     3,
     1,
     5,
     4,
     25,
     1,
     1],
    ['22024',
     1627759,
     '0022400604',
     'JAN 20, 2025',
     'BOS @ GSW',
     'W',
     29,
     8,
     14,
     0.571,
     1,
     3,
     0.333,
     0,
     0,
     0.0,
     1,
     3,
     4,
     2,
     0,
     0,
     2,
     2,
     17,
     27,
     1],
    ['22024',
     1627759,
     '0022400587',
     'JAN 18, 2025',
     'BOS vs. ATL',
     'L',
     43,
     9,
     27,
     0.333,
     2,
     9,
     0.222,
     4,
     5,
     0.8,
     6,
     5,
     11,
     8,
     2,
     0,
     4,
     2,
     24,
     -9,
     1],
    ['22024',
     1627759,
     '0022400577',
     'JAN 17, 2025',
     'BOS vs. ORL',
     'W',
     33,
     5,
     12,
     0.417,
     1,
     2,
     0.5,
     9,
     9,
     1.0,
     1,
     5,
     6,
     6,
     3,
     0,
     3,
     3,
     20,
     22,
     1],
    ['22024',
     1627759,
     '0022400562',
     'JAN 15, 2025',
     'BOS @ TOR',
     'L',
     33,
     4,
     16,
     0.25,
     1,
     1,
     1.0,
     1,
     2,
     0.5,
     2,
     5,
     7,
     4,
     1,
     0,
     2,
     3,
     10,
     -23,
     1],
    ['22024',
     1627759,
     '0022400542',
     'JAN 12, 2025',
     'BOS vs. NOP',
     'W',
     39,
     6,
     14,
     0.429,
     0,
     2,
     0.0,
     4,
     4,
     1.0,
     2,
     6,
     8,
     7,
     0,
     0,
     4,
     3,
     16,
     0,
     1],
    ['22024',
     1627759,
     '0022400528',
     'JAN 10, 2025',
     'BOS vs. SAC',
     'L',
     35,
     9,
     19,
     0.474,
     1,
     5,
     0.2,
     9,
     11,
     0.818,
     1,
     0,
     1,
     5,
     1,
     1,
     1,
     2,
     28,
     -9,
     1],
    ['22024',
     1627759,
     '0022400507',
     'JAN 07, 2025',
     'BOS @ DEN',
     'W',
     38,
     6,
     13,
     0.462,
     0,
     1,
     0.0,
     2,
     2,
     1.0,
     0,
     8,
     8,
     8,
     0,
     0,
     4,
     3,
     14,
     5,
     1],
    ['22024',
     1627759,
     '0022400487',
     'JAN 05, 2025',
     'BOS @ OKC',
     'L',
     40,
     8,
     19,
     0.421,
     1,
     6,
     0.167,
     4,
     4,
     1.0,
     0,
     4,
     4,
     3,
     1,
     1,
     3,
     2,
     21,
     -7,
     1],
    ['22024',
     1627759,
     '0022400449',
     'DEC 31, 2024',
     'BOS vs. TOR',
     'W',
     25,
     6,
     13,
     0.462,
     0,
     2,
     0.0,
     0,
     0,
     0.0,
     5,
     4,
     9,
     3,
     1,
     0,
     3,
     1,
     12,
     11,
     1],
    ['22024',
     1627759,
     '0022400437',
     'DEC 29, 2024',
     'BOS vs. IND',
     'L',
     36,
     13,
     21,
     0.619,
     2,
     6,
     0.333,
     3,
     5,
     0.6,
     0,
     4,
     4,
     6,
     1,
     0,
     2,
     3,
     31,
     -10,
     1],
    ['22024',
     1627759,
     '0022400420',
     'DEC 27, 2024',
     'BOS vs. IND',
     'W',
     37,
     16,
     24,
     0.667,
     6,
     11,
     0.545,
     6,
     6,
     1.0,
     3,
     2,
     5,
     3,
     4,
     0,
     1,
     0,
     44,
     30,
     1],
    ['22024',
     1627759,
     '0022400407',
     'DEC 25, 2024',
     'BOS vs. PHI',
     'L',
     43,
     10,
     23,
     0.435,
     3,
     6,
     0.5,
     0,
     3,
     0.0,
     1,
     6,
     7,
     4,
     2,
     0,
     5,
     4,
     23,
     -1,
     1],
    ['22024',
     1627759,
     '0022400393',
     'DEC 23, 2024',
     'BOS @ ORL',
     'L',
     37,
     15,
     29,
     0.517,
     1,
     7,
     0.143,
     4,
     6,
     0.667,
     2,
     7,
     9,
     4,
     3,
     0,
     5,
     4,
     35,
     6,
     1],
    ['22024',
     1627759,
     '0022400381',
     'DEC 21, 2024',
     'BOS @ CHI',
     'W',
     33,
     9,
     20,
     0.45,
     0,
     5,
     0.0,
     1,
     2,
     0.5,
     2,
     3,
     5,
     8,
     1,
     0,
     2,
     0,
     19,
     16,
     1],
    ['22024',
     1627759,
     '0022400363',
     'DEC 19, 2024',
     'BOS vs. CHI',
     'L',
     36,
     7,
     17,
     0.412,
     1,
     8,
     0.125,
     4,
     5,
     0.8,
     1,
     2,
     3,
     4,
     1,
     0,
     3,
     1,
     19,
     -19,
     1],
    ['22024',
     1627759,
     '0022401217',
     'DEC 15, 2024',
     'BOS @ WAS',
     'W',
     26,
     4,
     14,
     0.286,
     2,
     5,
     0.4,
     1,
     4,
     0.25,
     0,
     3,
     3,
     4,
     3,
     1,
     3,
     1,
     11,
     13,
     1],
    ['22024',
     1627759,
     '0022401205',
     'DEC 12, 2024',
     'BOS vs. DET',
     'W',
     30,
     6,
     12,
     0.5,
     1,
     2,
     0.5,
     1,
     1,
     1.0,
     1,
     8,
     9,
     6,
     1,
     0,
     4,
     1,
     14,
     30,
     1],
    ['22024',
     1627759,
     '0022400345',
     'DEC 07, 2024',
     'BOS vs. MEM',
     'L',
     35,
     10,
     14,
     0.714,
     2,
     3,
     0.667,
     0,
     1,
     0.0,
     1,
     2,
     3,
     6,
     1,
     0,
     5,
     3,
     22,
     -17,
     1],
    ['22024',
     1627759,
     '0022400335',
     'DEC 06, 2024',
     'BOS vs. MIL',
     'W',
     34,
     10,
     21,
     0.476,
     3,
     9,
     0.333,
     2,
     2,
     1.0,
     1,
     2,
     3,
     3,
     0,
     1,
     1,
     3,
     25,
     5,
     1],
    ['22024',
     1627759,
     '0022400319',
     'DEC 04, 2024',
     'BOS vs. DET',
     'W',
     39,
     10,
     21,
     0.476,
     1,
     6,
     0.167,
     7,
     11,
     0.636,
     1,
     5,
     6,
     9,
     3,
     0,
     4,
     0,
     28,
     16,
     1],
    ['22024',
     1627759,
     '0022400316',
     'DEC 02, 2024',
     'BOS vs. MIA',
     'W',
     31,
     8,
     21,
     0.381,
     4,
     11,
     0.364,
     9,
     10,
     0.9,
     4,
     3,
     7,
     4,
     1,
     0,
     2,
     2,
     29,
     23,
     1],
    ['22024',
     1627759,
     '0022400047',
     'NOV 29, 2024',
     'BOS @ CHI',
     'W',
     37,
     7,
     21,
     0.333,
     4,
     10,
     0.4,
     3,
     4,
     0.75,
     1,
     1,
     2,
     4,
     0,
     0,
     3,
     2,
     21,
     7,
     1],
    ['22024',
     1627759,
     '0022400281',
     'NOV 25, 2024',
     'BOS vs. LAC',
     'W',
     31,
     6,
     11,
     0.545,
     3,
     7,
     0.429,
     2,
     4,
     0.5,
     0,
     6,
     6,
     4,
     3,
     1,
     3,
     1,
     17,
     11,
     1],
    ['22024',
     1627759,
     '0022400271',
     'NOV 24, 2024',
     'BOS vs. MIN',
     'W',
     36,
     10,
     18,
     0.556,
     7,
     10,
     0.7,
     2,
     2,
     1.0,
     1,
     1,
     2,
     4,
     1,
     1,
     1,
     4,
     29,
     -1,
     1],
    ['22024',
     1627759,
     '0022400028',
     'NOV 22, 2024',
     'BOS @ WAS',
     'W',
     37,
     11,
     27,
     0.407,
     3,
     13,
     0.231,
     6,
     8,
     0.75,
     3,
     8,
     11,
     5,
     0,
     0,
     3,
     3,
     31,
     4,
     1],
    ['22024',
     1627759,
     '0022400021',
     'NOV 19, 2024',
     'BOS vs. CLE',
     'W',
     37,
     7,
     17,
     0.412,
     2,
     7,
     0.286,
     1,
     2,
     0.5,
     0,
     3,
     3,
     8,
     1,
     0,
     4,
     5,
     17,
     17,
     1],
    ['22024',
     1627759,
     '0022400230',
     'NOV 16, 2024',
     'BOS vs. TOR',
     'W',
     43,
     8,
     16,
     0.5,
     2,
     7,
     0.286,
     9,
     10,
     0.9,
     2,
     4,
     6,
     7,
     0,
     1,
     3,
     5,
     27,
     2,
     1],
    ['22024',
     1627759,
     '0022400218',
     'NOV 13, 2024',
     'BOS @ BKN',
     'W',
     36,
     8,
     19,
     0.421,
     2,
     5,
     0.4,
     6,
     9,
     0.667,
     2,
     10,
     12,
     4,
     1,
     0,
     0,
     2,
     24,
     27,
     1],
    ['22024',
     1627759,
     '0022400001',
     'NOV 12, 2024',
     'BOS vs. ATL',
     'L',
     36,
     14,
     22,
     0.636,
     3,
     6,
     0.5,
     6,
     10,
     0.6,
     2,
     3,
     5,
     2,
     1,
     0,
     6,
     3,
     37,
     0,
     1],
    ['22024',
     1627759,
     '0022400202',
     'NOV 10, 2024',
     'BOS @ MIL',
     'W',
     37,
     4,
     13,
     0.308,
     1,
     5,
     0.2,
     5,
     6,
     0.833,
     0,
     5,
     5,
     4,
     0,
     0,
     1,
     3,
     14,
     6,
     1],
    ['22024',
     1627759,
     '0022400132',
     'NOV 01, 2024',
     'BOS @ CHA',
     'W',
     37,
     8,
     19,
     0.421,
     0,
     6,
     0.0,
     9,
     10,
     0.9,
     3,
     3,
     6,
     5,
     1,
     1,
     1,
     3,
     25,
     11,
     1],
    ['22024',
     1627759,
     '0022400119',
     'OCT 30, 2024',
     'BOS @ IND',
     'L',
     43,
     11,
     30,
     0.367,
     1,
     11,
     0.091,
     2,
     4,
     0.5,
     0,
     6,
     6,
     5,
     2,
     2,
     3,
     4,
     25,
     -13,
     1],
    ['22024',
     1627759,
     '0022400104',
     'OCT 28, 2024',
     'BOS vs. MIL',
     'W',
     38,
     10,
     19,
     0.526,
     0,
     4,
     0.0,
     10,
     14,
     0.714,
     1,
     5,
     6,
     4,
     0,
     0,
     4,
     2,
     30,
     8,
     1],
    ['22024',
     1627759,
     '0022400089',
     'OCT 26, 2024',
     'BOS @ DET',
     'W',
     38,
     6,
     24,
     0.25,
     3,
     9,
     0.333,
     9,
     10,
     0.9,
     3,
     7,
     10,
     5,
     1,
     0,
     2,
     2,
     24,
     11,
     1],
    ['22024',
     1627759,
     '0022400073',
     'OCT 24, 2024',
     'BOS @ WAS',
     'W',
     30,
     10,
     20,
     0.5,
     3,
     6,
     0.5,
     4,
     5,
     0.8,
     1,
     7,
     8,
     3,
     4,
     0,
     2,
     1,
     27,
     22,
     1],
    ['22024',
     1627759,
     '0022400061',
     'OCT 22, 2024',
     'BOS vs. NYK',
     'W',
     30,
     7,
     18,
     0.389,
     5,
     9,
     0.556,
     4,
     4,
     1.0,
     2,
     5,
     7,
     1,
     1,
     0,
     1,
     3,
     23,
     23,
     1]]}]}

In [1]:
from nba_api.stats.endpoints import boxscoreadvancedv2
import pandas as pd

# Nikola Jokić
career = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id='0022400528')

# dictionary
results = career.get_dict()
data = pd.DataFrame(
    data=results['resultSets'][0]['rowSet'],
    columns=results['resultSets'][0]['headers'])
jb = data[data['PLAYER_ID'] == '1627759']

In [6]:
jb = data[data['PLAYER_ID'] == 1627759]
jb

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
14,0022400528,1610612738,BOS,Boston,1627759,Jaylen Brown,Jaylen,F,,35.000000:06,...,3.3,0.5,0.587,0.321,0.321,101.8,99.15,82.62,72,0.123

In [30]:
categories = ['E_USG_PCT', 'E_OFF_RATING', 'E_DEF_RATING', 'PACE_PER40', 'TS_PCT', 'AST_PCT']
jb[categories].iloc[0].to_dict()

{'E_USG_PCT': 0.31,
 'E_OFF_RATING': 139.4,
 'E_DEF_RATING': 119.8,
 'PACE_PER40': 79.08,
 'TS_PCT': 0.351,
 'AST_PCT': 0.25}

In [28]:
jb[['E_USG_PCT', 'E_OFF_RATING', 'E_DEF_RATING', 'PACE_PER40', 'TS_PCT', 'AST_PCT']]

    E_USG_PCT  E_OFF_RATING  E_DEF_RATING  PACE_PER40  TS_PCT  AST_PCT
18       0.31         139.4         119.8       79.08   0.351     0.25

In [16]:
from nba_api.stats.endpoints import teamestimatedmetrics
import pandas as pd
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
# Nikola Jokić
career = teamestimatedmetrics.TeamEstimatedMetrics(season='2024-25')

In [17]:
results = career.get_data_frames()

In [18]:
results = career.get_dict()
data = pd.DataFrame(
    data=results['resultSet']['rowSet'],
    columns=results['resultSet']['headers'])

In [19]:
data2 = data[['TEAM_NAME','TEAM_ID','E_OFF_RATING','E_DEF_RATING', 'E_PACE']]

In [20]:
data2

                 TEAM_NAME     TEAM_ID  E_OFF_RATING  E_DEF_RATING  E_PACE
0        Memphis Grizzlies  1610612763         114.6         109.4   106.9
1            Atlanta Hawks  1610612737         110.1         112.4   105.7
2            Chicago Bulls  1610612741         110.5         113.7   105.4
3       Washington Wizards  1610612764         103.6         115.9   104.0
4           Denver Nuggets  1610612743         117.2         111.9   102.7
5      Cleveland Cavaliers  1610612739         120.4         108.2   102.6
6    Oklahoma City Thunder  1610612760         116.7         104.0   102.5
7          Detroit Pistons  1610612765         111.2         109.9   102.4
8                Utah Jazz  1610612762         108.9         116.7   102.3
9          Milwaukee Bucks  1610612749         112.4         110.0   102.1
10    New Orleans Pelicans  1610612740         108.1         115.6   102.1
11          Indiana Pacers  1610612754         114.0         112.2   102.0
12       San Antonio Spurs  1610612759         110.7         112.5   102.0
13   Golden State Warriors  1610612744         111.2         109.1   101.8
14         Houston Rockets  1610612745         109.6         107.3   101.8
15         Toronto Raptors  1610612761         107.6         113.2   101.7
16        Sacramento Kings  1610612758         113.6         111.9   101.6
17        Dallas Mavericks  1610612742         112.5         111.7   101.6
18  Portland Trail Blazers  1610612757         108.2         112.7   101.6
19       Charlotte Hornets  1610612766         103.7         112.3   100.5
20             LA Clippers  1610612746         109.8         108.2   100.3
21      Los Angeles Lakers  1610612747         113.1         109.9   100.2
22  Minnesota Timberwolves  1610612750         112.1         108.4   100.0
23            Phoenix Suns  1610612756         113.3         114.9    99.9
24         New York Knicks  1610612752         115.9         112.4    99.8
25          Boston Celtics  1610612738         117.2         108.0    99.2
26      Philadelphia 76ers  1610612755         109.3         114.1    99.1
27           Orlando Magic  1610612753         105.1         107.2    98.9
28           Brooklyn Nets  1610612751         105.8         112.5    98.9
29              Miami Heat  1610612748         110.0         110.7    98.5

In [21]:
data2[['SEASON_ID']] = '22024'

/var/folders/fm/7zh52wdj2mx7v17vqtcy7ggc0000gn/T/ipykernel_79879/528538719.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2[['SEASON_ID']] = '22024'

In [22]:
data2

,TEAM_NAME,TEAM_ID,E_OFF_RATING,E_DEF_RATING,E_PACE,SEASON_ID
0,Memphis Grizzlies,1610612763,114.6,109.4,106.9,22024
1,Atlanta Hawks,1610612737,110.1,112.4,105.7,22024
2,Chicago Bulls,1610612741,110.5,113.7,105.4,22024
3,Washington Wizards,1610612764,103.6,115.9,104.0,22024
4,Denver Nuggets,1610612743,117.2,111.9,102.7,22024
5,Cleveland Cavaliers,1610612739,120.4,108.2,102.6,22024
6,Oklahoma City Thunder,1610612760,116.7,104.0,102.5,22024
7,Detroit Pistons,1610612765,111.2,109.9,102.4,22024
8,Utah Jazz,1610612762,108.9,116.7,102.3,22024
9,Milwaukee Bucks,1610612749,112.4,110.0,102.1,22024
10,New Orleans Pelicans,1610612740,108.1,115.6,102.1,22024
11,Indiana Pacers,1610612754,114.0,112.2,102.0,22024
12,San Antonio Spurs,1610612759,110.7,112.5,102.0,22024
13,Golden State Warriors,1610612744,111.2,109.1,101.8,22024
14,Houston Rockets,1610612745,109.6,107.3,101.8,22024
15,Toronto Raptors,1610612761,107.6,113.2,101.7,22024
16,Sacramento Kings,1610612758,113.6,111.9,101.6,22024
17,Dallas Mavericks,1610612742,112.5,111.7,101.6,22024
18,Portland Trail Blazers,1610612757,108.2,112.7,101.6,22024
19,Charlotte Hornets,1610612766,103.7,112.3,100.5,22024
20,LA Clippers,1610612746,109.8,108.2,100.3,22024
21,Los Angeles Lakers,1610612747,113.1,109.9,100.2,22024
22,Minnesota Timberwolves,1610612750,112.1,108.4,100.0,22024
23,Phoenix Suns,1610612756,113.3,114.9,99.9,22024
24,New York Knicks,1610612752,115.9,112.4,99.8,22024
25,Boston Celtics,1610612738,117.2,108.0,99.2,22024
26,Philadelphia 76ers,1610612755,109.3,114.1,99.1,22024
27,Orlando Magic,1610612753,105.1,107.2,98.9,22024
28,Brooklyn Nets,1610612751,105.8,112.5,98.9,22024
29,Miami Heat,1610612748,110.0,110.7,98.5,22024

In [4]:
from nba_api.stats.static import teams
import pandas as pd

# Get list of all NBA teams with IDs
nba_teams = teams.get_teams()
team_df = pd.DataFrame(nba_teams)

# Display team abbreviations & IDs
team_df[['id', 'abbreviation', 'full_name']]

            id abbreviation               full_name
0   1610612737          ATL           Atlanta Hawks
1   1610612738          BOS          Boston Celtics
2   1610612739          CLE     Cleveland Cavaliers
3   1610612740          NOP    New Orleans Pelicans
4   1610612741          CHI           Chicago Bulls
5   1610612742          DAL        Dallas Mavericks
6   1610612743          DEN          Denver Nuggets
7   1610612744          GSW   Golden State Warriors
8   1610612745          HOU         Houston Rockets
9   1610612746          LAC    Los Angeles Clippers
10  1610612747          LAL      Los Angeles Lakers
11  1610612748          MIA              Miami Heat
12  1610612749          MIL         Milwaukee Bucks
13  1610612750          MIN  Minnesota Timberwolves
14  1610612751          BKN           Brooklyn Nets
15  1610612752          NYK         New York Knicks
16  1610612753          ORL           Orlando Magic
17  1610612754          IND          Indiana Pacers
18  1610612755          PHI      Philadelphia 76ers
19  1610612756          PHX            Phoenix Suns
20  1610612757          POR  Portland Trail Blazers
21  1610612758          SAC        Sacramento Kings
22  1610612759          SAS       San Antonio Spurs
23  1610612760          OKC   Oklahoma City Thunder
24  1610612761          TOR         Toronto Raptors
25  1610612762          UTA               Utah Jazz
26  1610612763          MEM       Memphis Grizzlies
27  1610612764          WAS      Washington Wizards
28  1610612765          DET         Detroit Pistons
29  1610612766          CHA       Charlotte Hornets

In [4]:
import pandas as pd
from nba_api.stats.endpoints import leaguegamefinder
# Fetch all games for the current season
season = "2023-24"  # Modify this as needed
gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable=season)
games_df = gamefinder.get_data_frames()[0]

# # Keep only relevant columns
# games_df = games_df[["GAME_ID", "GAME_DATE", "TEAM_ID", "MATCHUP"]]

# # Split MATCHUP column to get home/away teams
# def extract_teams(row):
#     parts = row["MATCHUP"].split(" ")
#     if "vs." in row["MATCHUP"]:
#         home_team, away_team = parts[0], parts[2]
#     elif "@" in row["MATCHUP"]:
#         away_team, home_team = parts[0], parts[2]
#     return pd.Series({"home_team_abbr": home_team, "away_team_abbr": away_team})

# games_df[["home_team_abbr", "away_team_abbr"]] = games_df.apply(extract_teams, axis=1)

In [9]:
games_df

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42023,1610612738,BOS,Boston Celtics,0042300405,2024-06-17,BOS vs. DAL,W,240,106,...,0.850,15,36,51,25,9,2,7,15,18.0
1,42023,1610612742,DAL,Dallas Mavericks,0042300405,2024-06-17,DAL @ BOS,L,240,88,...,0.538,7,28,35,18,4,4,13,20,-18.0
2,42023,1610612738,BOS,Boston Celtics,0042300404,2024-06-14,BOS @ DAL,L,239,84,...,0.923,4,27,31,18,2,5,13,19,-38.0
3,42023,1610612742,DAL,Dallas Mavericks,0042300404,2024-06-14,DAL vs. BOS,W,240,122,...,0.682,13,39,52,21,7,2,8,17,38.0
4,42023,1610612742,DAL,Dallas Mavericks,0042300403,2024-06-12,DAL vs. BOS,L,240,99,...,0.875,7,36,43,15,5,1,8,17,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4378,12023,1610612742,DAL,Dallas Mavericks,0012300001,2023-10-05,DAL @ MIN,L,240,99,...,0.567,7,35,42,18,11,8,13,25,-12.0
4379,12023,104,PER,Perth Wildcats,2012300002,2023-09-08,PER @ GLI,W,238,127,...,0.872,10,29,39,25,10,8,21,23,15.0
4380,12023,1612709930,GLI,G League Ignite,2012300002,2023-09-08,GLI vs. PER,L,240,112,...,0.829,17,25,42,24,12,10,17,29,-15.0
4381,12023,104,PER,Perth Wildcats,2012300001,2023-09-06,PER @ GLI,L,239,105,...,0.846,21,19,40,27,13,8,21,21,-19.0
4382,12023,1612709930,GLI,G League Ignite,2012300001,2023-09-06,GLI vs. PER,W,240,124,...,0.870,11,32,43,27,12,10,22,23,19.0

In [10]:
# Keep only relevant columns
games_df = games_df[["GAME_ID", "GAME_DATE", "TEAM_ID", "MATCHUP"]]

# Split MATCHUP column to get home/away teams
def extract_teams(row):
    parts = row["MATCHUP"].split(" ")
    if "vs." in row["MATCHUP"]:
        home_team, away_team = parts[0], parts[2]
    elif "@" in row["MATCHUP"]:
        away_team, home_team = parts[0], parts[2]
    return pd.Series({"home_team_abbr": home_team, "away_team_abbr": away_team})

games_df[["home_team_abbr", "away_team_abbr"]] = games_df.apply(extract_teams, axis=1)

/var/folders/fm/7zh52wdj2mx7v17vqtcy7ggc0000gn/T/ipykernel_79879/2533903528.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games_df[["home_team_abbr", "away_team_abbr"]] = games_df.apply(extract_teams, axis=1)
/var/folders/fm/7zh52wdj2mx7v17vqtcy7ggc0000gn/T/ipykernel_79879/2533903528.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games_df[["home_team_abbr", "away_team_abbr"]] = games_df.apply(extract_teams, axis=1)

In [ ]:
import pandas as pd
from nba_api.stats.endpoints import leaguegamefinder

# Fetch all games for the current season
season = "2023-24"  # Modify this as needed
gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable=season)
games_df = gamefinder.get_data_frames()[0]

# Keep only relevant columns
games_df = games_df[["GAME_ID", "GAME_DATE", "TEAM_ID", "MATCHUP"]]

# Split MATCHUP column to get home/away teams
def extract_teams(row):
    parts = row["MATCHUP"].split(" ")
    if "vs." in row["MATCHUP"]:
        home_team, away_team = parts[0], parts[2]
    elif "@" in row["MATCHUP"]:
        away_team, home_team = parts[0], parts[2]
    return pd.Series({"home_team_abbr": home_team, "away_team_abbr": away_team})

games_df[["home_team_abbr", "away_team_abbr"]] = games_df.apply(extract_teams, axis=1)

# Merge with team IDs using the Teams table
conn = sqlite3.connect(DB_PATH)
teams_df = pd.read_sql("SELECT * FROM Teams;", conn)

# Create a mapping of abbreviations to team IDs
team_abbrev_to_id = dict(zip(teams_df["abbreviation"], teams_df["team_id"]))

# Map team abbreviations to team IDs
games_df["home_team_id"] = games_df["home_team_abbr"].map(team_abbrev_to_id)
games_df["away_team_id"] = games_df["away_team_abbr"].map(team_abbrev_to_id)

# Add season column
games_df["season"] = season

# Rename columns to match database schema
games_df.rename(columns={"GAME_ID": "game_id", "GAME_DATE": "game_date"}, inplace=True)

# Insert into SQLite
games_df.to_sql("Games", conn, if_exists="replace", index=False)
print("✅ Full season schedule inserted successfully!")

# Display table
import ace_tools as tools
tools.display_dataframe_to_user(name="NBA Full Season Schedule", dataframe=games_df)

conn.close()